# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

executors:
  node_executor: # declares a reusable executor for build and test
    docker:
      - image: circleci/node:11.1.0-browsers
    working_directory: ~/working_dir

jobs:
  build:
    executor: node_executor
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Persist the specified paths into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory.
          # This is a directory on the container which is taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - .

  test-with-coverage:
    executor: node_executor
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/working_dir

      - run: yarn test --code-coverage

      - store_test_results:
          path: build/reports/junit

      - store_artifacts:
          path: build/reports/junit

      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  build-docker-image:
    executor: node_executor
    steps:

    - attach_workspace:
        at: ~/working_dir
      
    - setup_remote_docker:
        docker_layer_caching: true
  
    - run: |
        docker build -t artun/gamezeug-tables .

  deploy-to-docker-hub:
    executor: node_executor
    steps:

    - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: ~/working_dir
      
    - setup_remote_docker:
        docker_layer_caching: true
  
    - run: |
        docker login -u $DOCKER_USER -p $DOCKER_PW
        docker push artun/gamezeug-tables

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test-with-coverage:
          requires:
            - build
      - build-docker-image:
          requires:
            - test-with-coverage
      - deploy-to-docker-hub:
          requires:
            - build-docker-image
